### ISSUE TITLE
Could you provide the txt file of msmt17 dataset?

### ISSUE THREAD

**Issue by AHU-ruijixiang** [FlyingRoastDuck/MetaAttack_AAAI21#1]
The homepage http://www.pkuvmc.com/publications/msmt17.html can't be visited,I can't find list_train.txt、list_val.txt、list_query.txt and list_gallery.txt.If you can provide these files,could you please send these to my email e20301175@stu.ahu.edu.cn?

**Comment by FlyingRoastDuck** [comment]
Hi, I have sent you an email.

**Comment by FlyingRoastDuck** [comment]
Hi, it seems that you give me the wrong email address. 
![image](https://user-images.githubusercontent.com/29745430/112917766-f2ef5f00-9135-11eb-92cb-c55a53684b25.png)

**Comment by AHU-ruijixiang** [comment]
> Hi, it seems that you give me the wrong email address.
> ![image](https://user-images.githubusercontent.com/29745430/112917766-f2ef5f00-9135-11eb-92cb-c55a53684b25.png)
I'm sorry about that,you can send it to another email address ruijixiang1996@163.com.Thank you very much
